using System.Globalization;
using System.Resources;

namespace LyricsDisplayer.Resources;

/// <summary>Strongly typed access to the App's default and future culture-specific string resources.</summary>
public static class Strings
{
    private static readonly ResourceManager Manager =
        new("LyricsDisplayer.Resources.Strings", typeof(Strings).Assembly);

    private static CultureInfo? _culture;

    public static CultureInfo? Culture
    {
        get => _culture;
        set => _culture = value;
    }

    private static string Get(string key) => Manager.GetString(key, _culture)!;

    public static string AppName => Get(nameof(AppName));
    public static string MainWindowTitle => Get(nameof(MainWindowTitle));
    public static string SettingsWindowTitle => Get(nameof(SettingsWindowTitle));
    public static string EditorWindowTitle => Get(nameof(EditorWindowTitle));
    public static string FatalErrorTitle => Get(nameof(FatalErrorTitle));
    public static string MainOpenBuiltInEditor => Get(nameof(MainOpenBuiltInEditor));
    public static string ShowDesktopLyrics => Get(nameof(ShowDesktopLyrics));
    public static string OpenLrcExternally => Get(nameof(OpenLrcExternally));
    public static string Settings => Get(nameof(Settings));
    public static string OpenLyricsWindow => Get(nameof(OpenLyricsWindow));
    public static string ExitLyricsDisplayer => Get(nameof(ExitLyricsDisplayer));
    public static string HideDesktopLyrics => Get(nameof(HideDesktopLyrics));
    public static string SettingsGeneral => Get(nameof(SettingsGeneral));
    public static string SettingsLyricsOverlay => Get(nameof(SettingsLyricsOverlay));
    public static string SettingsLyricsWindow => Get(nameof(SettingsLyricsWindow));
    public static string SettingsMediaController => Get(nameof(SettingsMediaController));
    public static string SettingsEditor => Get(nameof(SettingsEditor));
    public static string SettingsDebug => Get(nameof(SettingsDebug));
    public static string MenuCurrentLine => Get(nameof(MenuCurrentLine));
    public static string MenuAllLyrics => Get(nameof(MenuAllLyrics));
    public static string LyricsDisplay => Get(nameof(LyricsDisplay));
    public static string OneLine => Get(nameof(OneLine));
    public static string TwoLines => Get(nameof(TwoLines));
    public static string Overlay => Get(nameof(Overlay));
    public static string LockPosition => Get(nameof(LockPosition));
    public static string ClickThrough => Get(nameof(ClickThrough));
    public static string TimingMinus500Earlier => Get(nameof(TimingMinus500Earlier));
    public static string TimingMinus100Earlier => Get(nameof(TimingMinus100Earlier));
    public static string TimingPlus100Later => Get(nameof(TimingPlus100Later));
    public static string TimingPlus500Later => Get(nameof(TimingPlus500Later));
    public static string EditorClear => Get(nameof(EditorClear));
    public static string EditorSetTime => Get(nameof(EditorSetTime));
    public static string EditorTimingAuthoring => Get(nameof(EditorTimingAuthoring));
    public static string EditorShiftAllTimestamps => Get(nameof(EditorShiftAllTimestamps));
    public static string EditorSelectedLine => Get(nameof(EditorSelectedLine));
    public static string EditorUndo => Get(nameof(EditorUndo));
    public static string EditorRedo => Get(nameof(EditorRedo));
    public static string EditorInsertAbove => Get(nameof(EditorInsertAbove));
    public static string EditorInsertBelow => Get(nameof(EditorInsertBelow));
    public static string EditorAppendRow => Get(nameof(EditorAppendRow));
    public static string EditorDeleteRow => Get(nameof(EditorDeleteRow));
    public static string EditorSourceTitle => Get(nameof(EditorSourceTitle));
    public static string EditorSourceArtist => Get(nameof(EditorSourceArtist));
    public static string EditorTitleOverride => Get(nameof(EditorTitleOverride));
    public static string EditorArtistOverride => Get(nameof(EditorArtistOverride));
    public static string EditorLyricsColumn => Get(nameof(EditorLyricsColumn));
    public static string EditorTimestampColumn => Get(nameof(EditorTimestampColumn));
    public static string EditorPreservedEntries => Get(nameof(EditorPreservedEntries));
    public static string EditorSave => Get(nameof(EditorSave));
    public static string EditorClose => Get(nameof(EditorClose));
    public static string EditorWarnings => Get(nameof(EditorWarnings));
    public static string EditorErrors => Get(nameof(EditorErrors));
    public static string EditorValidationAdvisory => Get(nameof(EditorValidationAdvisory));
    public static string EditorSaveClosePrompt => Get(nameof(EditorSaveClosePrompt));
    public static string EditorSaveCloseTitle => Get(nameof(EditorSaveCloseTitle));
    public static string EditorExternalConflictPrompt => Get(nameof(EditorExternalConflictPrompt));
    public static string EditorExternalConflictTitle => Get(nameof(EditorExternalConflictTitle));
    public static string EditorWatcherUnavailable => Get(nameof(EditorWatcherUnavailable));
    public static string EditorUnavailableForEditing => Get(nameof(EditorUnavailableForEditing));
    public static string EditorAuthoritativeLrcMissing => Get(nameof(EditorAuthoritativeLrcMissing));
    public static string EditorLrcMissingBufferPreserved => Get(nameof(EditorLrcMissingBufferPreserved));
    public static string EditorCurrentLrcCannotBeChecked => Get(nameof(EditorCurrentLrcCannotBeChecked));
    public static string EditorAuthoritativeFilesChanged => Get(nameof(EditorAuthoritativeFilesChanged));
    public static string EditorFilesChangedExternally => Get(nameof(EditorFilesChangedExternally));
    public static string EditorSaved => Get(nameof(EditorSaved));
    public static string EditorSaveFailedDirty => Get(nameof(EditorSaveFailedDirty));
    public static string EditorExternalLrcUnavailable => Get(nameof(EditorExternalLrcUnavailable));
    public static string EditorReloadedExternalVersion => Get(nameof(EditorReloadedExternalVersion));
    public static string EditorSetTimeUnavailable => Get(nameof(EditorSetTimeUnavailable));
    public static string EditorPlaybackTimeCannotBeAdded => Get(nameof(EditorPlaybackTimeCannotBeAdded));
    public static string EditorDocumentTimestampsCouldNotShift => Get(nameof(EditorDocumentTimestampsCouldNotShift));
    public static string EditorNegativeTimestampShift => Get(nameof(EditorNegativeTimestampShift));
    public static string EditorSelectedRowTimestampsCouldNotShift => Get(nameof(EditorSelectedRowTimestampsCouldNotShift));
    public static string EditorStatusWithDetails => Get(nameof(EditorStatusWithDetails));
    public static string EditorLineLocation => Get(nameof(EditorLineLocation));
    public static string EditorDocumentLocation => Get(nameof(EditorDocumentLocation));
    public static string EditorValidationError => Get(nameof(EditorValidationError));
    public static string EditorValidationWarning => Get(nameof(EditorValidationWarning));
    public static string EditorValidationDiagnosticLine => Get(nameof(EditorValidationDiagnosticLine));
    public static string Debug => Get(nameof(Debug));
    public static string DebugTrack => Get(nameof(DebugTrack));
    public static string DebugPlaybackSource => Get(nameof(DebugPlaybackSource));
    public static string DebugSourceTrackId => Get(nameof(DebugSourceTrackId));
    public static string DebugEffectiveTitle => Get(nameof(DebugEffectiveTitle));
    public static string DebugEffectiveArtist => Get(nameof(DebugEffectiveArtist));
    public static string DebugLocalTrackId => Get(nameof(DebugLocalTrackId));
    public static string DebugStorage => Get(nameof(DebugStorage));
    public static string DebugLyricsLibrary => Get(nameof(DebugLyricsLibrary));
    public static string DebugSqliteIndex => Get(nameof(DebugSqliteIndex));
    public static string DebugTransport => Get(nameof(DebugTransport));
    public static string DebugNativeHostConnection => Get(nameof(DebugNativeHostConnection));
    public static string DebugPlayback => Get(nameof(DebugPlayback));
    public static string DebugState => Get(nameof(DebugState));
    public static string DebugLyricsProvider => Get(nameof(DebugLyricsProvider));
    public static string DebugLyricsSource => Get(nameof(DebugLyricsSource));
    public static string DebugAvailability => Get(nameof(DebugAvailability));
    public static string DebugTiming => Get(nameof(DebugTiming));
    public static string DebugLoadedFrom => Get(nameof(DebugLoadedFrom));
    public static string DebugLocalAssociation => Get(nameof(DebugLocalAssociation));
    public static string DebugLogs => Get(nameof(DebugLogs));
    public static string DebugApplicationLogs => Get(nameof(DebugApplicationLogs));
    public static string DebugOpenLogsFolder => Get(nameof(DebugOpenLogsFolder));
    public static string DebugCrashReports => Get(nameof(DebugCrashReports));
    public static string DebugOpenCrashReportsFolder => Get(nameof(DebugOpenCrashReportsFolder));
    public static string DebugRawPlaybackSnapshot => Get(nameof(DebugRawPlaybackSnapshot));
    public static string DebugRawLyricsSnapshot => Get(nameof(DebugRawLyricsSnapshot));
    public static string ValueNotAvailable => Get(nameof(ValueNotAvailable));
    public static string ValuePlaying => Get(nameof(ValuePlaying));
    public static string ValuePaused => Get(nameof(ValuePaused));
    public static string ValueAvailable => Get(nameof(ValueAvailable));
    public static string ValueUnavailable => Get(nameof(ValueUnavailable));
    public static string ValueTimed => Get(nameof(ValueTimed));
    public static string ValueUntimed => Get(nameof(ValueUntimed));
    public static string DebugPlaybackStateFormat => Get(nameof(DebugPlaybackStateFormat));
    public static string DebugNoPlaybackSnapshot => Get(nameof(DebugNoPlaybackSnapshot));
    public static string DebugNoRawLyricsSnapshot => Get(nameof(DebugNoRawLyricsSnapshot));
    public static string DebugPendingUnknown => Get(nameof(DebugPendingUnknown));
    public static string DebugYoutubeMusicRuntime => Get(nameof(DebugYoutubeMusicRuntime));
    public static string DebugLocalLibrary => Get(nameof(DebugLocalLibrary));
    public static string DebugLocalLibraryUnavailable => Get(nameof(DebugLocalLibraryUnavailable));
    public static string DebugLocalLibraryExternalLrcRejected => Get(nameof(DebugLocalLibraryExternalLrcRejected));
    public static string DebugLocalLibraryLastValidLyricsRetained => Get(nameof(DebugLocalLibraryLastValidLyricsRetained));
    public static string DebugLocalLibraryFileUnavailable => Get(nameof(DebugLocalLibraryFileUnavailable));
    public static string DebugLocalLibraryFileTemporarilyUnavailable => Get(nameof(DebugLocalLibraryFileTemporarilyUnavailable));
    public static string DebugAssociationNotChecked => Get(nameof(DebugAssociationNotChecked));
    public static string DebugAssociationFound => Get(nameof(DebugAssociationFound));
    public static string DebugAssociationNotFound => Get(nameof(DebugAssociationNotFound));
    public static string DebugAssociationLibraryUnavailable => Get(nameof(DebugAssociationLibraryUnavailable));
    public static string DebugAssociationIndexUnavailable => Get(nameof(DebugAssociationIndexUnavailable));
    public static string DebugAssociationBrokenRecord => Get(nameof(DebugAssociationBrokenRecord));
    public static string DebugAssociationDuplicate => Get(nameof(DebugAssociationDuplicate));
    public static string DebugImportImported => Get(nameof(DebugImportImported));
    public static string DebugImportAlreadyLocal => Get(nameof(DebugImportAlreadyLocal));
    public static string DebugImportNotTimed => Get(nameof(DebugImportNotTimed));
    public static string DebugImportBlockedByBrokenRecord => Get(nameof(DebugImportBlockedByBrokenRecord));
    public static string DebugImportFilesPersistedIndexFailed => Get(nameof(DebugImportFilesPersistedIndexFailed));
    public static string DebugImportFailed => Get(nameof(DebugImportFailed));
    public static string DebugExternalLrcRejected => Get(nameof(DebugExternalLrcRejected));
    public static string DebugLocalLrcUnavailable => Get(nameof(DebugLocalLrcUnavailable));
    public static string DebugExternalLrcTemporarilyUnavailable => Get(nameof(DebugExternalLrcTemporarilyUnavailable));
    public static string DebugFolderOpened => Get(nameof(DebugFolderOpened));
    public static string DebugFolderOpenFailed => Get(nameof(DebugFolderOpenFailed));
    public static string TransportWaitingForNativeHost => Get(nameof(TransportWaitingForNativeHost));
    public static string TransportConnected => Get(nameof(TransportConnected));
    public static string TransportDisconnectedWaitingForNativeHost => Get(nameof(TransportDisconnectedWaitingForNativeHost));
    public static string ConnectionErrorSeeLogs => Get(nameof(ConnectionErrorSeeLogs));
    public static string MainWaitingForPlaybackSource => Get(nameof(MainWaitingForPlaybackSource));
    public static string MainWaitingForLyricsEllipsis => Get(nameof(MainWaitingForLyricsEllipsis));
    public static string MainWaitingForLyrics => Get(nameof(MainWaitingForLyrics));
    public static string MainNoLyricLinesAvailable => Get(nameof(MainNoLyricLinesAvailable));
    public static string MainSynchronizedLyrics => Get(nameof(MainSynchronizedLyrics));
    public static string LyricsUnavailable => Get(nameof(LyricsUnavailable));
    public static string LyricsUntimed => Get(nameof(LyricsUntimed));
    public static string LyricsLocalFileMissing => Get(nameof(LyricsLocalFileMissing));
    public static string LrcNoCurrentLocalFile => Get(nameof(LrcNoCurrentLocalFile));
    public static string LrcExternalOpened => Get(nameof(LrcExternalOpened));
    public static string LrcPathUnavailable => Get(nameof(LrcPathUnavailable));
    public static string LrcWatchingCurrent => Get(nameof(LrcWatchingCurrent));
    public static string LrcWatcherUnavailable => Get(nameof(LrcWatcherUnavailable));
    public static string LrcExternalReloaded => Get(nameof(LrcExternalReloaded));
    public static string LrcExternalRejectedRetained => Get(nameof(LrcExternalRejectedRetained));
    public static string LrcExternalUnavailableRetained => Get(nameof(LrcExternalUnavailableRetained));
    public static string LrcCheckingLatestChange => Get(nameof(LrcCheckingLatestChange));
    public static string LrcUnavailableReloadIfRestored => Get(nameof(LrcUnavailableReloadIfRestored));
    public static string LrcCannotReadRetained => Get(nameof(LrcCannotReadRetained));
    public static string LrcPathNotAbsolute => Get(nameof(LrcPathNotAbsolute));
    public static string LrcFileUnavailable => Get(nameof(LrcFileUnavailable));
    public static string LrcCouldNotBeOpened => Get(nameof(LrcCouldNotBeOpened));
    public static string LrcCouldNotOpenType => Get(nameof(LrcCouldNotOpenType));
    public static string FatalCrashReportSavedTo => Get(nameof(FatalCrashReportSavedTo));
    public static string FatalCrashReportCouldNotWriteAttemptedPath => Get(nameof(FatalCrashReportCouldNotWriteAttemptedPath));
    public static string FatalCrashReportCouldNotWriteDirectory => Get(nameof(FatalCrashReportCouldNotWriteDirectory));
    public static string FatalErrorMessage => Get(nameof(FatalErrorMessage));
    public static string RecoverableOperationFailure => Get(nameof(RecoverableOperationFailure));
}
